### ISSUE TITLE
ThreeD_Pose_Estimation

### ISSUE THREAD

**Issue by sunjunlishi** [fengju514/Face-Pose-Net#1]
where is the dnn model file. and so that  get 3d pos and 3d face shape ?

**Comment by iacopomasi** [comment]
Dear @sunjunlishi,
have you followed the instructions properly?

In particular, it seems to me you are missing these two important points:

- **Important:** In order to download both FPN code and the renderer use git clone --recursive
- **Important:** Please download the learned models from `https://www.dropbox.com/s/r38psbq55y2yj4f/fpn_new_model.tar.gz?dl=0` and make sure that the FPN models are stored in the folder fpn_new_model.

If I follow this, it works on my machine.

**Comment by sunjunlishi** [comment]
sorry .thanks
