### ISSUE TITLE
Some questions about model ground truth

### ISSUE THREAD

**Issue by xjcvip007** [fengju514/Face-Pose-Net#34]
Hi, thanks for your amazing work! One question, you just say that 'The detected landmarks were then used to compute the 6DoF labels for the images in this sets' in your paper, so I want to ask that how can you get the 6Dof labels using landmarks? In some issues, you mention that by using generic 3D face model, but may be you can explain it in more detail. Looking for your reply~

**Comment by TalHassner** [comment]
@xjcvip007 Thank you for the interest in this work and the kind words. 

6DoF pose was computed from landmark annotations (manual or estimated via a detector) using the same technique used in our previous work. See MATLAB pseudo code at the bottom of this [older project page](https://talhassner.github.io/home/publication/2014_MVAP), and read more details in some of our other papers, including the [original frontalization paper](https://talhassner.github.io/home/publication/2015_CVPR_1) and a more recent, [follow up](https://talhassner.github.io/home/publication/2017_FG).

In broad terms, the process is similar to camera calibration only using detected facial landmarks instead of, say, detected checkerboard corners for a standard calibration rig. The relevant details, including the math involved, are covered in most computer vision textbooks and also in the [documentation of the OpenCV calibration functions](https://docs.opencv.org/2.4/doc/tutorials/calib3d/camera_calibration/camera_calibration.html) (though note that some technical details may be different in our implementation and others'). 

I hope this helps. Good luck.

**Comment by xjcvip007** [comment]
Wow, thank you for answering this question in person. I would like to understand those works you linked first, Thank you~
